# creating workflow for running github-actions pipeline

name: Workflow to run Terraform code
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  pull_request:
    branches: [master]
    types: [closed]
  push:
    branches: [master]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  Docker-testing:
    name: 'Docker Testing'
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: hostname
